name: Pull Request Checks

on:
  pull_request:
    types: [opened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test

  link-to-jira:
    runs-on: ubuntu-latest
    needs: [lint-test]
    env:
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
    steps:
      - name: Extract Jira ticket key from branch name
        id: extract-ticket-key
        run: |
          branch_name=${{ github.event.pull_request.head.ref }}
          regex='(^[A-Z]+-[0-9]+)'
          if [[ $branch_name =~ $regex ]]; then
            echo "Jira ticket key is ${BASH_REMATCH[1]}"
            echo "::set-output name=ticket_key::${BASH_REMATCH[1]}"
          else
            echo "No Jira ticket key found in branch name"
          fi
      - name: Link pull request to Jira
        uses: atlassian/gajira-link-action@v2
        with:
          issueKey: ${{ steps.extract-ticket-key.outputs.ticket_key }}
          accessToken: ${{ secrets.JIRA_TOKEN }}
          pullRequestUrl: ${{ github.event.pull_request.html_url }}
      - name: Link commit to Jira
        run: |
          ticket_key=${{ steps.extract-ticket-key.outputs.ticket_key }}
          if [ -z "$ticket_key" ]; then
            echo "No Jira ticket key found in branch name"
            exit 1
          fi
          echo "Linking commit to Jira"
          curl -s --user "${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_TOKEN }}" \
               --request POST \
               --url "https://<your-jira-domain>/rest/api/3/issue/${ticket_key}/comment" \
               --header 'Accept: application/json' \
               --header 'Content-Type: application/json' \
               --data-raw '{
                   "body": "This commit is associated with this Jira ticket: '${ticket_key}'.\nCommit URL: '${{ github.event.pull_request.head.repo.html_url }}/commit/${{ github.event.pull_request.head.sha }}'"
               }'